- docs/resources/resource_definition.md
- examples/resources/humanitec_resource_definition/resource.tf
- internal/provider/provider.go
> Small doc changes

- README.md
- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
Handle resource references https://docs.humanitec.com/reference/concepts/resources/references and add a couple more tests.
> feat: handle resource references

- Makefile
- docs/resources/resource_account.md
- docs/resources/resource_definition.md
- examples/resources/humanitec_resource_account/import.sh
- examples/resources/humanitec_resource_definition/import.sh
- go.mod
- go.sum
- internal/provider/humanitec_client.go
- internal/provider/humanitec_data.go
- internal/provider/resource_account_resource.go
- internal/provider/resource_definition_resource.go
Document the import capabilities and fix hum client-go compile issues.
> chore: document import

- internal/provider/humanitec_client_test.go
- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
Support `boolean` properties in resource definitions.
> fix: support boolean properties

- internal/provider/resource_account_resource.go
- internal/provider/resource_artefact_version.go
> Update explanation on delete resources that are not deleted from the remote api

- .github/workflows/test.yaml
- go.mod
- go.sum
> chore: go 1.20

- docs/index.md
- go.mod
- go.sum
- internal/provider/humanitec_client.go
- internal/provider/humanitec_client_test.go
- internal/provider/provider.go
Option to disable ssl verification.
> feat: option to disable ssl verification

- internal/provider/resource_application.go
Remove active resources before removing the app so resource definitions can be removed once the deletion has finished.
> fix: remove resources before the app

- docs/resources/application.md
- go.mod
- go.sum
- internal/provider/resource_application.go
- internal/provider/resource_application_test.go
Support customizing the initial app env using https://api-docs.humanitec.com/#tag/Application/paths/~1orgs~1%7BorgId%7D~1apps/post
> feat: support customizing the initial app env

- internal/provider/humanitec_client.go
- internal/provider/humanitec_client_test.go
- internal/provider/provider.go
- internal/provider/resource_application.go
- internal/provider/resource_application_test.go
- internal/provider/resource_value.go
When an application was deleted manually, the provider crashed with a null pointer exception.
> fix: missing application crashes the provider

- go.mod
- go.sum
- internal/provider/resource_account_resource.go
- internal/provider/resource_application.go
- internal/provider/resource_definition_resource.go
Support deleting unreferenced resource accounts.
> feat: support resource account deletion

- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
Support for https://developer.humanitec.com/platform-orchestrator/resources/graph/#co-provision-resources
> feat: support resource co-provisioning

- docs/resources/resource_definition.md
- docs/resources/resource_definition_criteria.md
- internal/provider/resource_definition_criteria_resource.go
- internal/provider/resource_definition_criteria_resource_test.go
- internal/provider/resource_definition_resource.go
Support matching criteria resource `class` https://api-docs.humanitec.com/#tag/MatchingCriteria
> feat: suppert resource definition classes

- internal/provider/resource_application.go
Deleting an active resource can return a 202, which means the resource was marked for deletion, but the deletion hasn't completed yet.
Retry until are deletes are successful or return a 404.
> fix: handle 202 when deleting active resource

- docs/resources/resource_definition.md
- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
This supports `secret_refs` field in `resource_definition` resources.
> Secret refs resource def

- internal/provider/resource_definition_resource.go
Allow in-place secret_refs changes
> fix(resource_definition): allow in-place secret_refs changes

- go.mod
- go.sum
- internal/provider/resource_environment_type.go
https://humanitec.atlassian.net/browse/WAL-9608
> Update env-type description using tf

- internal/provider/resource_environment_type_test.go
- internal/provider/resource_environment_type_user_test.go
https://humanitec.atlassian.net/browse/WAL-9608
> Added test case for env-type description update

- .gitignore
Add VS Code configuration directory to gitignore file
> chore: add .vscode dir to .gitignore

- internal/provider/source_ip_ranges_data_source.go
- internal/provider/source_ip_ranges_data_source_test.go
Update the list of Humanitec Source IPs.
> feat: update humanitec source IPs

- docs/resources/user.md
- internal/provider/resource_user.go
The role is called `artefactContributor`
> fix: artefactContributor spelling

- go.mod
- go.sum
- internal/provider/resource_definition_criteria_resource.go
- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
- internal/provider/utils.go
Update `resource_definition` to handle update of `driver_type`.
> feat(res-def): allow update of driver_type

- docs/index.md
- examples/provider/provider.tf
- internal/provider/resource_definition_resource_test.go
adding the required providers in the usage example
as well as fixing a broken acceptance test
> add required providers

- go.mod
> feat: go 1.23

- .github/workflows/test.yaml
- internal/provider/resource_definition_resource_test.go
- internal/provider/resource_secret_store_test.go
- internal/provider/resource_value_test.go
Adjust test to use GCP SM as primary secret store
> fix: adjust tests for Operation mode
