humanitec/terraform-provider-humanitec

- docs/index.md
- docs/resources/resource_definition.md
- internal/provider/humanitec_client.go
- internal/provider/humanitec_client_test.go
- internal/provider/humanitec_data.go
- internal/provider/provider.go
- internal/provider/resource_account_resource.go
- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
Support the static driver, which has no dedicated input schema and instead re-assembles the resource type output schema. 
Additionally fetch resource drivers & types only once per execution.
> feat: static driver support

- internal/provider/resource_definition_resource.go
The PATCH endpoint is merging the provided inputs with the existing inputs, which isn't something we want here.
Use the newly added PUT method instead of to ensure the tf state matches the state in Humanitec.
> fix: use PUT to update resources

- internal/provider/resource_application.go
- internal/provider/resource_definition_resource.go
If a resource is removed using the UI (or API), currently the provider treat this as a terminal error.
For convenience, I propose to just remove the state instead of forcing people to run `terraform state rm ...`
The official AWS Terraform provider has the same behaviour  (example: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/s3/bucket.go#L959) so it's a known way to manage the state when things are removed outside Terraform.
Tests: I am not sure how you'd like to modify the test suite to integrate this external call to delete the resources, so let me know how you wish to proceed.
Tested Manually:
- Create Res def. and App, and then remove manually:
- Run Apply:
- Expected: Recreate
- Actual: Recreate
- Run Destroy: 
- Expected: Nothing
- Actual: Nothing …
> Remove halt state for App and Resource definition when removed outside Terraform

- docs/resources/application.md
- internal/provider/resource_application.go
Fixing references to old nomenclature.
> WAL-6866: Terraform Provider documentation mentions "Modules" instead of "Workloads"

- internal/provider/resource_value.go
- internal/provider/resource_value_test.go
Fix running a terraform plan when the value was deleted manually.
> fix: plan when value was deleted manually

- internal/provider/resource_definition_criteria_resource.go
Otherwise changing the `force_delete` attribute caused:
```
╷
│ Error: UNSUPPORTED_OPERATION
│
│   with humanitec_resource_definition_criteria...
│
│ Updating an ResourceDefinitionCriteria is currently not supported
╵
```
> fix: updating force delete resource criteria

- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
Fix a crash that happened when using a resource definition without inputs.
> fix: resource definitions without inputs

- docs/resources/resource_account.md
- internal/provider/resource_account_resource.go
- internal/provider/resource_definition_resource_test.go
Those credentials usually contain sensitive values.
> fix: mark resource account credentials as sensitive

- docs/resources/resource_definition.md
- examples/resources/humanitec_resource_definition/resource.tf
- go.mod
- go.sum
- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
Support json input for resource definition values and secrets, which no longer requires type casting base on the driver schema and therefor allows also attributes not defined in the schema.
> feat: support json inputs for resource definitions

- internal/provider/resource_application.go
- internal/provider/resource_definition_criteria_resource.go
- internal/provider/resource_definition_resource.go
The Humanitec resource cleanup logic improved and there is no longer a need to explicitly remove active resources.
As resource deletion now happens after the app deletion, I've increased the deletion timeout for res def / res def criteria to ensure deleting an app and matched res def still works as expected.
> fix: remove active resource deletion

- .github/workflows/test.yaml
- docs/index.md
- internal/provider/provider.go
- internal/provider/provider_test.go
- internal/provider/resource_application_test.go
- internal/provider/resource_definition_resource_test.go
- internal/provider/resource_pipeline.go
- internal/provider/resource_pipeline_test.go
- internal/provider/resource_registry.go
- internal/provider/resource_registry_test.go
- internal/provider/resource_value_test.go
Support `HUMANITEC_ORG` to specific the Humanitec Organization. Mark `HUMANITEC_ORG_ID` as deprecated.
> Replace HUMANITEC_ORG_ID with HUMANITEC_ORG

- internal/provider/resource_application.go
Handle a 404 while trying to delete an application, which can occur when the app has been deleted manually.
> fix(application): 404 during delete

- go.mod
- go.sum
- internal/provider/humanitec_client_test.go
- internal/provider/humanitec_data.go
- internal/provider/resource_account_resource.go
- internal/provider/resource_application.go
- internal/provider/resource_application_test.go
- internal/provider/resource_application_user.go
- internal/provider/resource_definition_criteria_resource.go
- internal/provider/resource_definition_resource.go
- internal/provider/resource_environment_type.go
- internal/provider/resource_environment_type_user.go
- internal/provider/resource_resource_driver.go
I needed an updated client in the terraform provider so that I can use a new API behavior. However this brings in the client with new operation ids for resources, apps, and envs! So I must first upgrade this repo over to the new names and keep the changes isolated.
> chore: updated humanitec client and update code to use new SDK operation ids

- internal/provider/resource_service_user_token_test.go
Streamlined datetime formatting for platform compatibility: Removed milliseconds from expires_at property to align with platform requirements, ensuring stable acceptance tests
> fix(test): expires at property has too less milliseconds digits

- internal/provider/resource_application_user.go
- internal/provider/resource_application_user_test.go
- internal/provider/resource_environment_type.go
- internal/provider/resource_environment_type_user.go
- internal/provider/resource_environment_type_user_test.go
- internal/provider/resource_user.go
Properly handle 404s when a user application or environment type role was deleted manually.
> fix: handle 404 when reading user roles

- internal/provider/resource_agent.go
- internal/provider/resource_agent_test.go
Changing the agent id requires the agent resource to be recreated.
> fix: agent id change requires recreate

- docs/resources/application.md
- docs/resources/application_user.md
- docs/resources/environment_type_user.md
- docs/resources/user.md
- internal/provider/resource_application.go
- internal/provider/resource_application_user.go
- internal/provider/resource_environment_type_user.go
- internal/provider/resource_user.go
- Add details about possible values for role variables
- Add warning about the impact of deleting an application when changing the default environment after creation.
> doc: Add documentation details on role valid values and warning on application deletion

- internal/provider/resource_registry.go
- internal/provider/resource_registry_test.go
There is currently when using a `humanitec_registry` resource with `creds`.
With a definition like:
```hcl
resource "humanitec_registry" "my" {
id        = "my"
type      = "amazon_ecr"
creds = {
username = "aws"
password = "key"
}
}
```
The previous implementation would send a quoted string the API.
```json
{ "creds": { "username": "\"aws\"", "password": "\"key\"" } }
```
Fix this to be properly encoded strings.
```json
{ "creds": { "username": "aws", "password": "key" } }
```
> fix: double encoding in registry creds

- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
This fixes an issue with secret references in resource definition which were non-set if not unknown (so when no specified).
This is still not a full fix as in case of secret references which are both references and values, secret references are not set.
The problem here is that secret references are complex nested objects and comparison is a mess.
> fix: set secret refs always if no value is specified

- internal/provider/resource_environment.go
When a new set is deploy, the value of this field changes and TF constantly demands the environment to be recreated.
```
-/+ resource "humanitec_environment" "platform_staging" {
~ from_deploy_id = "17d496de579fb118" -> "17d4933cec88acc7" # forces replacement
id             = "staging"
name           = "Staging"
}
```
> fix(environment): don't set from_deploy_id

- internal/provider/resource_definition_resource.go
Removing the modifier was missed in https://github.com/humanitec/terraform-provider-humanitec/pull/92
> fix: mark resource definition driver type as updatable

- internal/provider/resource_account_resource.go
- internal/provider/resource_account_resource_test.go
- internal/provider/resource_agent.go
- internal/provider/resource_agent_test.go
- internal/provider/resource_application_test.go
- internal/provider/resource_application_user_test.go
- internal/provider/resource_environment_type_user_test.go
- internal/provider/resource_key_test.go
- internal/provider/resource_resource_class.go
- internal/provider/resource_resource_class_test.go
- internal/provider/resource_resource_driver.go
- internal/provider/resource_resource_driver_test.go
- internal/provider/resource_rule.go
- internal/provider/resource_rule_test.go
- internal/provider/resource_secret_store.go
- internal/provider/resource_secret_store_test.go
- internal/provider/resource_value_test.go
This makes the provider able to handle deletion of resources outside TF.
Integration tests have been added where they were missing.
> fix: handle resources deleted outside TF provider

- go.mod
- go.sum
- internal/provider/provider.go
This PR introduces the retryhttp library which we've been using with success in our internal services.
This adds 2 retries for any idempotent request failures or timeouts.
> fix: adds 2 http retries to humanitec client requests

- internal/provider/resource_secret_store.go
- internal/provider/resource_secret_store_test.go
This PR resolves an issue preventing updates to the id of the secret store. Previously, providers attempted to modify the id field directly, which the API does not permit. The new behavior replaces the entire resource instead.
Example output:
```
$terraform apply
humanitec_secretstore.ss: Refreshing state... [id=saml-test-ss-1]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
Terraform will perform the following actions:
-/+ resource "humanitec_secretstore" "ss" {
~ id      = "saml-test-ss-1" -> "saml-test-ss-2" # forces replacement
}
Plan: 1 to add, 0 to change, 1 to destroy.
Do you want to perform these actions?
Terraform will perform the actions described …
```
> fix: replace secret store on id change

- docs/resources/application.md
- examples/resources/humanitec_application/resource.tf
- go.mod
- go.sum
- internal/provider/resource_account_resource.go
- internal/provider/resource_application.go
- internal/provider/resource_application_test.go
- internal/provider/resource_rule_test.go
- internal/provider/resource_value_test.go
This PR introduces a breaking change in the application resource by removing initial environment creation. Since this feature was originally added due to a Humanitec limitation, there is no reason to continue supporting it.
From now on, applications will be created without any environments by default. Environments can be created separately via Terraform using the humanitec_environment resource. This change improves the integrity and flexibility of the Humanitec Terraform Provider.
Old TF code example:
```hcl
resource "humanitec_application" "example" {
id   = "example"
name = "An example app"
env = {
id   = "development"
name = "An example environment"
type = "development"
}
}
```
New TF code example:
```hcl
resource "humanitec_application" "example" {
id   = "example"
name = "An example …
```
> feat: remove init env from application resource

- internal/provider/resource_value.go
- internal/provider/resource_value_test.go
This PR adds additional filters to the values list to exclude all app values when reading environment variables. This ensures that if an environment variable is manually deleted, the app value will not be mismatched, and the state of that environment variable will be removed accordingly
> fix: mismatch app value when env value is missing on read

- go.mod
- go.sum
- internal/provider/provider.go
- internal/provider/resource_application.go
- internal/provider/resource_application_test.go
- internal/provider/resource_application_user.go
- internal/provider/resource_environment_type_user.go
- internal/provider/resource_user.go
- internal/provider/users_data_source.go
This leverages the [new API endpoint](https://api-docs.humanitec.com/#tag/Application/operation/patchApplication) to update the application name to allow updating an application name also via CLI.
Ticket: https://humanitec.atlassian.net/browse/WAL-10958.
> feat(application): allow updating name

- docs/resources/application_user.md
- docs/resources/environment_type_user.md
- internal/provider/resource_application_user.go
- internal/provider/resource_environment_type_user.go
This is not creating the `resource_group` yet, but it's aligning doc about the `user_id` field in [`application_user`](https://registry.terraform.io/providers/humanitec/humanitec/latest/docs/resources/application_user) that could be a `user or group ID`, aligned with the associated API docs now: https://api-docs.humanitec.com/#tag/UserRole/operation/createUserRoleInApp.
https://developer.humanitec.com/platform-orchestrator/security/authentication/#groups
> Update `user_id` doc for `application_user` and `environment_type_user`: "user or group"

- docs/resources/resource_definition.md
- examples/resources/humanitec_resource_definition/resource.tf
- go.mod
- go.sum
- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
This enables to specify params to inject when a co-provisioned resource is provisioned.
Ticket: https://humanitec.atlassian.net/browse/WAL-11222
> feat(def): allow set params into co-provisioned resources

- internal/provider/resource_definition_resource.go
- internal/provider/resource_definition_resource_test.go
Testing #120 I realized a bug when `is_dependent` was not set in the definition, as it was computed by the schema doesn't define it.
This should fix it.
> fix(def): provision.is_dependent is computed
